FROM golang:1.24.0-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o agent ./cmd/agents

FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata wget

ENV TZ=Asia/Jakarta

RUN addgroup -g 1001 appuser && \
    adduser -D -u 1001 -G appuser appuser

WORKDIR /app

COPY --from=builder /app/agent .

COPY --chown=appuser:appuser config/agent-config.yaml ./config/agent-config.yaml

RUN mkdir -p /home/appuser && chown -R appuser:appuser /home/appuser

USER appuser

EXPOSE 8081

CMD ["./agent"]
